site_name: Scheems
site_description: Auto generate APIs for your relational databases.
site_author: Anand Krishna
theme:
  name: "material"

repo_name: anand2312/scheems
repo_url: https://github.com/anand2312/scheems/
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - HTTP Methods and corresponding Routes: http_methods.md
  - Bulk Endpoints: bulk_endpoints.md
  - API Reference: api_reference.md

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"
  - pymdownx.tabbed
  - pymdownx.highlight
